// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWmPzrXgZwU3iEVsArqEzilYh0tJWWddc',
    appId: '1:626132539773:android:2a5fc377b6460dc7f15414',
    messagingSenderId: '626132539773',
    projectId: 'oddlet-app',
    storageBucket: 'oddlet-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCnQm18Z791gJ_XhzA1fkbPS9eAd0-DA8',
    appId: '1:626132539773:ios:f23e9450f93520aef15414',
    messagingSenderId: '626132539773',
    projectId: 'oddlet-app',
    storageBucket: 'oddlet-app.firebasestorage.app',
    androidClientId: '626132539773-prikoer1eri3rhc4n1vkagqug4qe3oft.apps.googleusercontent.com',
    iosClientId: '626132539773-4f9735hathma01qu7hp5a6suff1n3cr3.apps.googleusercontent.com',
    iosBundleId: 'com.castlebell.oddlet',
  );
}
